global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi_todos"
    metrics_path: /metrics
    static_configs:
      - targets: ["api_todo:8000"]
        labels:
          service: api_todo
          env: develop
